### ISSUE TITLE
Transport/serializer source?

### ISSUE THREAD

**Issue by drub0y** [inter8ection/Obvs#1]
So you mention ActiveMQ/NetMQ support and you have separate binary packages for those up on NuGet which is awesome, but are you going to publish the repos containing the source for those as well?

I would seriously like to consider implementing Azure Service Bus support for this, but I would like to be able to look at your ActiveMQ implementation for example as a reference.

**Comment by drub0y** [comment]
Duh, neeeeeever mind... you already did! In my excitement to check this out I totally spaced and was only looking at your popular repos where they aren't listed instead of all of them. :+1:

**Comment by inter8ection** [comment]
Hey, that sounds great! I did have that one on the list, but was working on the RabbitMQ one. I should probably add a page to the wiki for people who want to implement new transports. Basically you need 3 things: MessageSource implementation, MessagePublisher implementation, and any fluent config extensions for your particular transport.

**Comment by drub0y** [comment]
Yup! I've been working on some stuff that was designed very similar to this (centered around IObservable as well), but you're a lot further along with the overall architecture and it's looking really good! Now I'm thinking I'll just ditch my work and focus on getting the Azure SB transport implementation going and save myself a ton of work. :D

Do you think it would be valuable to open an issue here on the core repo that we can track Azure SB progress against? Ultimately it will be its own repo, but just getting started at least people coming into the core repo will know there's already some work going on out there around it. Just let me know and I'll open one up.

**Comment by inter8ection** [comment]
It's great to have someone already considering the problem validate the design, so thanks for the positive feedback! :) Good call on opening an issue on the main repo so people are aware it's being worked on - please go ahead.

**Comment by drub0y** [comment]
Done! #2

I'm going to start with just Queues, but, personally, Topics/Subscriptions are more interesting to me so after I get my beak wet with support for Queues I can dive into that.
