### ISSUE TITLE
Request/Response Correlation - Introduce a Provider Model?

### ISSUE THREAD

**Issue by drub0y** [inter8ection/Obvs#11]
So Obvs has a baked in approach to setting `RequesterId` (and `RequestId` if not specified) when `ServiceBusClient::GetResponses` is called. There's no way to override this behavior at present. Two things:

  1. Right now the logic only sets `RequestId` if it's not already set. However, `RequesterId` is always set and overrides any value that the application might have already specified. I would argue that `RequesterId` should use the same rule of only overwriting if not already set. At a bare minimum, I would love to see this changed as soon as possible with the goal of allowing the application itself to decide this on a per-request basis if it wants to.
  2. How do you feel about introducing a provider model for this so that people can plug in their own implementations? I imagine something like:

```
public interface IRequestCorrelationProvider
{
    void ProvideRequestCorrelationIds(IRequest request);
}
```

Then a companion configuration API:
```
public interface ICanSpecifyRequestCorrelationProvider : IWhateverMakesSenseHere
{
    IWhateverMakesSenseHere WithRequestCorrelationProvider(IRequestCorrelationProvider provider);
}
```
I can send a PR around this if it's something you're in agreement with.

**Comment by inter8ection** [comment]
Hey just on holiday at the moment, but reviewed your changes, will leave a comment on PR.

**Comment by inter8ection** [comment]
This was completed a while back I think, but I didn't close the issue. Nice!
