### ISSUE TITLE
Consider adding NUnitTestAdapter NuGet package to Obvs.Tests project

### ISSUE THREAD

**Issue by drub0y** [inter8ection/Obvs#13]
Right now people have to have the NUnit Test Adapter VS Extension installed to be able to run the tests easily in VS. I personally didn't have it installed, but installed it for now. Consider adding the adapter as a reference to [the NUnitTestAdapter package](https://www.nuget.org/packages/NUnitTestAdapter/) instead so alleviate people from having to install anything just to be able to run the tests in VS.

**Comment by inter8ection** [comment]
Hey, I normally have either ReSharper and NCrunch test runners installed, but happy to add this package if it helps, committed https://github.com/inter8ection/Obvs/commit/c123f06086dd2ff22683bcbe954aa0ffb7dcd7f9

Been keen to try https://github.com/fixie/fixie for a while, but NUnit is usually my default out of habit.

Please close if you're happy.

**Comment by drub0y** [comment]
Yeah, we usually use XUnit, which has an adapter package too, and then we have a bunch of legacy MSTest stuff, so I just never had the need to install the NUnit adapter. 

Anyway, I just pulled latest, built and the adapter package installed and all the tests auto-ran for me in VS, so I think this is good! Thanks! :+1:
