### ISSUE TITLE
Deprecated package reference on Nuget (Rx-Linq)

### ISSUE THREAD

**Issue by fabianoliver** [inter8ection/Obvs#26]
Hi,

seems Obvs 3.0.1.58 (current version) on Nuget references Rx-Linq, which as far as I know is deprecated/unlisted and has been replaced by System.Reactive.Linq.

Any plans to update this here & on Nuget?

As for me, I'm getting exceptions when using both (e.g. reference the latest System.Reactive) as Obvs seems to fail finding/loading the old Rx DLLs, in spite of having assembly redirects in place. Haven't spent much time on the issue yet as I figured an Obvs upgrade to the latest Rx libraries probably makes more sense anyway?

**Comment by inter8ection** [comment]
Hello, yes you are correct, upgrading Obvs to the latest System.Reactive libraries would make sense. I had put any upgrading on hold while they sorted out .Net core, as I assumed the next version of Obvs would be based on .Net core, but haven't had time to pursue it. You can see the issue open here https://github.com/inter8ection/Obvs/issues/25

There are currently no plans to upgrade, but I look into it.

**Comment by megakid** [comment]
Fixed in https://github.com/inter8ection/Obvs/pull/27
