### ISSUE TITLE
Separating interfaces in to a separate library

### ISSUE THREAD

**Issue by chandmk** [inter8ection/Obvs#3]
Currently I am running into loading errors while the library is doing assembly scanning and loading.
Moving messages to a separate library and referencing Obvs solved the issue.

Separating Obvs interfaces to its own library would reduce scanning related errors.

**Comment by inter8ection** [comment]
Hello, thanks for the feedback! Do you think you'd be able to supply some more details or a stacktrace for the error so I can take a look?

I did have some issues relating to scanning on the project I am using Obvs in, and it was due to it trying to load 3rd party assemblies which required a licence.

To get round this at the time, I added a quick fluent config method which takes a string which it does a .Contains on the assembly name it is loading types from, e.g.

```
    IServiceBus serviceBus = ServiceBus.Configure()
                .WithActiveMQEndpoints<ITestMessage>()
                    .Named("Obvs.TestService")
                    .UsingQueueFor<ICommand>()
                    .ConnectToBroker("tcp://localhost:61616")
                    .SerializedAsJson()
                    .FilterMessageTypeAssemblies("MyProject.Messages.")
                    .AsClientAndServer()
                .Create();
```

My plan is to add an overload that takes a Func at some point to allow more configurable filtering.

**Comment by chandmk** [comment]
Yes separate assembly works fine.
May be there should be a configurable convention that can provide a filter for identifying events, commands and messages.  Default conventions are also not a bad idea.  A simple convention like types ending with word "Event", "Command", "Message" can be used as messages might work nicely.

Following is the stack trace.  I am trying to create the bus in an asp.net project.

[ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.]
   System.Reflection.RuntimeModule.GetTypes(RuntimeModule module) +0
   System.Reflection.RuntimeModule.GetTypes() +9
   System.Reflection.Assembly.GetTypes() +70
   Obvs.Configuration.MessageTypes.<Get>b__1(Assembly assembly) +10
   System.Linq.<SelectManyIterator>d__8`2.MoveNext() +213
   System.Linq.WhereSelectEnumerableIterator`2.MoveNext() +190
   System.Linq.Buffer`1..ctor(IEnumerable`1 source) +310
   System.Linq.Enumerable.ToArray(IEnumerable`1 source) +77
   Obvs.Serialization.Json.JsonMessageDeserializerFactory.Create(String assemblyNameContains) +236
   Obvs.NetMQ.Configuration.NetMqServiceEndpointProvider`1.CreateEndpointClient() +77
   Obvs.Configuration.ServiceBusFluentCreator.WithEndpoints(IServiceEndpointProvider serviceEndpointProvider) +20
   Obvs.NetMQ.Configuration.NetMqFluentConfig`1.AsClientAndServer() +22
   fc.web.MvcApplication.Application_Start() in k:\Projects\fc\fc.web\Global.asax.cs:26

[HttpException (0x80004005): Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.]
   System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app) +9932409
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +118
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +172
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +352
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +296

[HttpException (0x80004005): Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +9910264
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +101
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +316

**Comment by inter8ection** [comment]
Hi, I will improve the error message so at least you know which assembly is causing it to throw, at the moment it isn't clear. If you specify FilterMessageTypeAssemblies it should fix your current issue for now.

**Comment by inter8ection** [comment]
I have updated Obvs from 1.4.3 onwards to include the name of the assembly giving the error if you'd like to retry?

**Comment by inter8ection** [comment]
Closing this for now until original poster replies.
