### ISSUE TITLE
Add async version of IMessagePublisher::Publish

### ISSUE THREAD

**Issue by drub0y** [inter8ection/Obvs#6]
Right now `IMessagePublisher` only offers a synchronous version of the `Publish` method. Since many implementations are likely to be making a network request as a result of this method being called it would be beneficial to offer an async version of this method. 

Suggested method signature:
```
Task PublishAsync(TMessage message);
```

I could see it going two ways:

  1. Simply add an additional method to the interface and allow each implementation to provide the best possible implementation for both the synchronous version and the asynchronous version. This has a slight downside of requiring all `IMessagePublisher` implementations to provide an implementation of both versions of the method which could theoretically allow them to optimize for both scenarios, but I suspect you'd see most implementations implementing the sync version by simply calling the async version and blocking on the `Task::Result`. Vice versa, and worse for most cases, they could implement the async version by calling the sync version and wrapping the result in `Task::FromResult`.
  2. Take a "hard" stance and keep the API surface lean by replacing the existing synchronous signature with the asynchronous one.

My personal vote would be for option number 2.

**Comment by inter8ection** [comment]
Yes I gave it some thought at the start and initially left it with a synchronous call for simplicity, as I wanted to ensure I knew about failures straight away before I published another message. The caller could then wrap it up in a Task or queue if they wanted. As you may have seen in the NetMQ implementation I decided to queue the published messages up and do the blocking call in a loop on its own thread.

However now that things have moved a bit, I'd certainly consider option 2 if we thought on balance it would be the better choice for publishing.

This would then need to propagate up to the ServiceBus which is effectively looping through and calling send or publish on the appropriate endpoints, raising an AggregateException with any errors.

**Comment by inter8ection** [comment]
I suppose part of the consideration is whether the caller should or Obvs should ensure deterministic ordering of the messages it is given to publish, i.e. a queue.

**Comment by drub0y** [comment]
> Yes I gave it some thought at the start and initially left it with a synchronous call for simplicity, as I wanted to ensure I knew about failures straight away before I published another message. The caller could then wrap it up in a Task or queue if they wanted. As you may have seen in the NetMQ implementation I decided to queue the published messages up and do the blocking call in a loop on its own thread.

So I don't think there's anything about making it async that prevents that at all. If the caller cares, then they just await the resulting `Task` before continuing. If a particular implementation is using a local queue, let's say for message batching (AzureSB has this feature), it may choose to return synchronously, but it's still going to deliver that message to the remote queue in the order it was pushed onto the local queue.

> I suppose part of the consideration is whether the caller should or Obvs should ensure deterministic ordering of the messages it is given to publish, i.e. a queue.

Again, I don't think there's anything about making the method async that necessarily means things will get out of order. The caller simply needs to wait for the resulting `Task` to complete before sending the next message in the sequence.

**Comment by inter8ection** [comment]
I suspect most transport API's, although having a sync method signature will actually handover to an IO thread underneath.

I can change the contract to option 2, but would likely do this underneath in the current implementations to satisfy the contract:
```
public Task PublishAsync(TMessage message)
 {
	 Publish(message);
	 return Task.FromResult(true);
 }
```
Do you agree this is preferable to _Task.Run(() = > Publish(message))_ in the case where the transport API doesn't have an async publish method? I don't want to tie up a task per publish, as I'd rather leave that up to the caller to decide.

On the question of ordering, I still think that adding it to a queue internally and having a single Task as the publisher is a good policy for transport implementations. I did this in NetMQ specifically because it was sending/receiving on the same thread.

**Comment by inter8ection** [comment]
Hey, just to confirm, I will be making this change soon so it should be in Obvs 1.5.

**Comment by drub0y** [comment]
@inter8ection Hey, sorry for lack of reply! Out on vacation this week. 

> Do you agree this is preferable to Task.Run(() = > Publish(message)) in the case where the transport API doesn't have an async publish method? I don't want to tie up a task/thread per publish, as I'd rather leave that up to the caller to decide.

Yes, I agree that simply returning `Task.FromResult` in the case of the underlying transport only offering a synchronous implementation would be the best approach. There's no point in spinning up a background task in those cases as that's still going to consume a CPU thread. So you'd just be paying the price of context switching for no real gain. Just do the work on the calling thread and return synchronously.

> On the question of ordering, I still think that adding it to a queue internally and having a single Task as the publisher is a good policy for transport implementations. I did this in NetMQ specifically because it was sending/receiving on the same thread, but retaining ordering rather than leaving it to the caller to deal with would be preferable.

Sure, I think that's a detail that will differ from transport to transport. Again, with Azure SB I'm just going to be building a `BrokeredMessage` and calling something like `QueueClient::SendAsync`. Now, it's behavior will depend on various options I've chosen. If there's no batching, that's pretty much going to be a direct network request to send out the message to the queue. If there's batching, it's going to push onto a local queue buffer and eventually send out in a batch after *N* messages have accumulated or some amount of time has passed without receiving a new message.

**Comment by inter8ection** [comment]
Hi, OK this work has been completed and all libraries updated to 1.5. I have experimented with using a shared EventLoopScheduler for each Endpoint's publishers in the AMQ and NetMQ transport implementations, but stuck with Task.FromResult for Rabbit. 

There are a few minor breaking changes as a result of adding Serialization sub-namespace, and a new logging extension config point (and a new NLog implementation library which logs messages in and out of each endpoint).

Let me know if I can mark this issue and Closed, and if you have any problems upgrading.

**Comment by drub0y** [comment]
Upgraded one of my local branches to 1.5 and synched everything up and it seems to be working great. Will push up as soon as my other changes are ready. I will close out this issue as I think it's done now!

**Comment by inter8ection** [comment]
Great!
