### ISSUE TITLE
Should IServiceBus, IServiceBusClient, IServiceEndpoint et al. be IDisposable?

### ISSUE THREAD

**Issue by drub0y** [inter8ection/Obvs#7]
Would it be smart to make this family of types subtype `IDisposable`? They all may have underlying resources that need to be cleaned up in some way. Right now the typical use case is these objects are going to live for the lifetime of the application and when the app goes away it's going to terminate all those resources anyway so "who cares?", but it might be wise to give the option to be able to clean up such resources more gracefully on-demand.

There is more than one way to tackle this, not only subtyping `IDisposable` and forcing it on all implementations, but I just wanted to start a discussion to see what anyone else has to say about it.

**Comment by inter8ection** [comment]
You're right that the typical usage is the IServiceBus exists for the lifetime of the application, so I only extended IDisposable on the publisher and source classes. I am not opposed to cascading this down from the ServiceBus, through the Endpoints, but I don't really want IServiceBus to extend IDisposable as then one caller could call Dispose when another was still using it. So I would probably just make the ServiceBus class implement it.

**Comment by inter8ection** [comment]
One option is to create a new interface which extends `IServiceBus` and `IDisposable` called `IDisposableServiceBus`, that the fluent config returns. Then the developer could use this to dispose of the ServiceBus/Endpoints/Sources/Publishers at the end of the application's lifetime, but safely inject a non-disposable `IServiceBus` into classes as they would now. Thoughts?

**Comment by drub0y** [comment]
Yeah, ya know it's funny 'cause that crossed my mind, but I didn't want to suggest it because it just didn't "feel" right, but now that you've said it too I wonder if it's maybe the right idea after all.

What if the answer is not to even worry about making it obvious at all? What if the answer is just that people who configure the bus know they can cast the `IServiceBus` to `IDisposable` **if** they really care about cleaning it up later? Then it's just a matter of implementing `IDisposable` on the `ServiceBus` class and that's it? I would assume most people are going to be using it as a singleton like you said and then that means that app termination is the only time it's going to be cleaned up which means there doesn't even need to be graceful cleanup. Also, I imagine a lot of people will also likely just be configuring the bus and then stuffing it into their favorite DI container which already does run time `is IDisposable` checks on any dependencies to gracefully dispose of them whenever the lifetime scope ends, so those don't need a strong interface chain either. So maybe the "manual" clean up scenario is really just a more advanced scenario that can simply be handled by some documentation?

**Comment by inter8ection** [comment]
> Also, I imagine a lot of people will also likely just be configuring the bus and then stuffing it into their favorite DI container which already does run time is IDisposable checks on any dependencies to gracefully dispose of them whenever the lifetime scope ends, so those don't need a strong interface chain either. So maybe the "manual" clean up scenario is really just a more advanced scenario that can simply be handled by some documentation?

Agreed, cool, OK I will make the ServiceBus implement `IDisposable` but not expose/extend it as part of the interface.

**Comment by drub0y** [comment]
So I immediately thought, "ok, great, it's `IDisposable` what's that really buy us?". So then I read back through the thread a bit and just want to make sure we're on the same page. 

`ServiceBus`'s implementation would need walk through all the `IServiceEndpoint` instances in `_endpoints` and try to cast those dispose of those. Then `ServiceBusClient` also needs to be `IDisposable` so that `ServiceBus` can call `base.Dispose()` on that and then `ServiceBusClient`'s implementation needs to walk through all the `IServiceEndpointClient` instances in its `_endpointClients` and do the same thing and so on through the graph. 'Cause the whole purpose is to get down to the `MessageSource/Publisher` instances, which hold any actual transport resources open, to see if those are `IDisposable` and give those a chance to clean up gracefully. Right? 

Now would you make those other types actually subtype `IDisposable` directly or would you introduce "testing" of each instance to see if it implements `IDisposable` all the way down through the various implementations?

FWIW, one little gotcha I see is that you'd have to make sure your `Service[Client]EndpointLoggingProxy` class also implements `IDisposable` and delegates to the underlying `IServiceEndpoint[Client]`.

**Comment by inter8ection** [comment]
Yes, we're on the same page, I had done the changes to see how they would cascade down when you first raised the possibility but hadn't committed, and it's pretty much as you describe above, including the logging proxy gotcha (as I made the endpoints extend `IDisposable`).

`MessageSource` and `MessagePublisher` already extend `IDisposable` and I don't see any issue with the endpoints extending it as they shouldn't be exposed beyond the configuration stage anyway.

**Comment by inter8ection** [comment]
OK all committed here https://github.com/inter8ection/Obvs/commit/7f5e4482ebee0f5bd528eac3afd740e0c57b59ec and published to NuGet.org as Obvs 1.6.2

**Comment by drub0y** [comment]
Great stuff, thanks!

**Comment by drub0y** [comment]
FWIW, I see this working great in my tests.

**Comment by inter8ection** [comment]
Great, thanks for reporting it :)
