### ISSUE TITLE
Serialization design discussion

### ISSUE THREAD

**Issue by drub0y** [inter8ection/Obvs#9]
So the current design of `IMessageSerializer::Serialize` enforces nothing more than that a particular implementation can transform any `object` into *any* other `object`. The implementations that exist already in [Obvs.Serialization](https://github.com/inter8ection/Obvs.Serialization) seem to adhere to an unspoken contract of returning either a `string` or a `byte[]`. Then, the various `MessagePublisher` implementations have to then test the return type and make a further decision about exactly how those types are going to be passed through the message.

This feels rather "loose". It's also suboptimal because the data types force a fixed size realization of what otherwise lies in buffers underneath `Streams` which is also going to result in a lot of copying and creation of a lot more garbage that has to be GC'd. 

Have you thought at all about changing this interface? My proposal would be to change the signature to `void Serialize(Stream destinationStream, object message)` instead. Then it's up to the `MessagePublisher` to provide the most optimal `Stream` implementation for themselves and all of the serializer implementations would just write to the `Stream`. JSON.NET supports this (you just layer a `TextWriter` over the `Stream`), the Protobuf implementation is already writing to a temp `MemoryStream` and then having to do that copying I was talking about, and of course the `XmlSerializer` supports this as well.

On the `MessagePublisher` side, in the Azure Service Bus implementaiton I would just supply a `MemoryStream` and looking at the ActiveMQ implementation you could actually write a simple `Stream` implementation that wraps their `IStreamMessage` very easily for example.

So what's the downside to this? Well, everything would be `bytes` data and any "special" treatment that a particular implementation might provide when it knows it's a `string` would be lost, but I don't personally see any value in that as it's all just `bytes` at the end of the day and I'd rather see maximum performance possible here.

Now, the flip side to this is obviously `IMessageDeserializer::Deserialize` which currently takes `object` and returns `TMessage` and obviously that too should then change to `TMessage Deserialize(Stream sourceStream)`.

**Comment by drub0y** [comment]
I've made these changes in some local branches. It was super easy. I'll wait to hear your thoughts before I send any PRs though.

**Comment by inter8ection** [comment]
Hey, really liked your ideas about supporting serialization to/from Stream, and have baked them into the latest 1.5.1 releases as overloads for now, but the current methods just wrap the Stream methods.

I do agree that using object to/from is a bit loose, and there is an unspoken contract regarding string or byte[], and that I do then use that to determine the message type that the transport uses. But herein lies the issue, I do want the behavior where the Active MQ transport decides where to use ITextMessage or IByteMessage based on the type of data it's sending. Perhaps there's a missing abstraction somewhere, but I didn't want to experiment with IStreamMessage for two reasons 1) I like being able to inspect text messages on the wire, nice for debugging your domain events 2) I want MessageSource to be usable for custom Endpoints where you want to subscribe to messages from an external non-Obvs service, and the norm here is again using IText/IByteMessage.

I am hoping in time Obvs can act as glue between Obvs, and non-Obvs based services, because that's how I am already using it in production, and it's pretty neat.

Your proposals also made me examine the Serialization libraries, and I made the following improvements:
- Added unit tests project *cough*
- Fixed XmlSerializer so it is non-generic and now actually usable. It caches the typed serializers underneath to improve performance.
- Added fluent config for Xml serialization which wasn't available due to the above.
- Lastly added the new hip serialization format, MsgPack

**Comment by drub0y** [comment]
Cool. I'd love to see what you're doing in 1.5.1 and be able to build/take a dependency directly on that source (or even contribute back). Are you planning on pushing that branch up to the repo??

**Comment by inter8ection** [comment]
All committed to master already, and packages on nuget. Started off adding a Tests project to test the Stream overloads you suggested, then realised it was pretty much done already so just went ahead and committed.

**Comment by drub0y** [comment]
Oh, nice... you move fast! So this obviously solves my immediate concerns, thank you.

I think maybe the abstraction you're looking for is one where the serializer can "advertise" the formats it's capable of producing and the transport can then opt-in to a more friendly format if it wants to. So, maybe an `IMessageSerializationProvider` interface that has a `bool SupportsSerializer(Type)` method and an `TSerializer GetSerializer<TSerializer>()`. 

Then you have `IMessageStreamSerializer` with `void Serializer(Stream, object)` and `IMessageTextSerializer` with `void Serialize(TextWriter, object)` rather than the one `IMessageSerializer`. Then transport implementations that want to/can provide a better "experience" for text based messages can check if the serializer that's configured can actually provide that by calling `SupportsSerializer(typeof(IMessageTextSerializer))` and, if so, it would call `GetSerializer<IMessageTextSerializer>()` and works with that from there to provide the best experience for itself. IMHO can't see any point in a `byte[]` specific interface as `Stream` gives you the bytes you want, it's just not forcing the extra allocation/memcpy of the fixed size array to be able to return the result. That said, if you really thought it worthwhile, just introduce an `IMessageByteSerializer` too.

That said, IMHO, I don't think this particular argument warrants introducing all of this complexity:

>  1) I like being able to inspect text messages on the wire, nice for debugging your domain events

If you're inspecting on the wire, then just look at the data through the right "lens". It's all bytes right? If you know it's text, then decode it as text with whatever inspection software you're using. If you're saying that ActiveMQ provides some kind of GUI experience that is more friendly because it's ITextMessage then, yeah, ok. But do you really want to introduce this complexity and performance issues into your framework just for a nicer debugging experience?

This argument I'm not sure I understand, but I would like to:

>  2) I want MessageSource to be usable for custom Endpoints where you want to subscribe to messages from an external non-Obvs service, and the norm here is again using IText/IByteMessage.

Are you saying that you would receive `IText/ByteMessage` via some kind of "raw" `MessageSource` implementation which is choosing not to do any actual serialization? If so, that's a cool idea. That said, I don't think the serializer infrastructure is even in play at that point as you would just be returning whatever subtype of `IMessage` was coming off the queue, but I guess your point is that you'd need it to have been put there as an `ITextMessage` in the first place?

**Comment by inter8ection** [comment]
>If you're inspecting on the wire, then just look at the data through the right "lens". It's all bytes right? If you know it's text, then decode it as text with whatever inspection software you're using.

Yeah you could start sticking the serialization format in some meta property in the message, and then use that to decide whether you could decode it to text or not, I do this for the NetMQ implementation, but I'd rather use what's optimal for the transport's own API and in the AMQ case it would be ITextMessage.

> do you really want to introduce this complexity and performance issues into your framework just for that slightly nicer experience during debugging

Well I don't see it as complexity as such, almost the opposite, I feel like it would force me to use a stream implementation for a transport which differentiates between text and bytes already. I haven't profiled this, but it's not causing me any performance issues yet.

> This argument I'm not sure I understand, but I would like to

So in my company we already have a lot of services which publish messages onto AMQ that aren't using Obvs. Some text messages, some byte messages. The current AMQ implementation of `MessageSource` allows me to receive and deserialize messages from these sources.

**Comment by inter8ection** [comment]
The good thing is now the serializers support both stream and non-stream methods, the transport implementation can choose whatever they prefer.

Btw, despite my tests I did have some bugs with the XML deserializers after my change above, where I was using a `MemoryStream` and `Encoding.UTF8.GetBytes` to convert the text received into a stream before calling the stream-based deserialization method underneath.

`There is an error in XML document (0, 0). ---> System.Xml.XmlException: There is no Unicode byte order mark. Cannot switch to Unicode.`

So I would need to be careful in my assumptions when converting strings which aren't streams _to_ streams.

Are you ok to close this one for now?

**Comment by drub0y** [comment]
Yes, I'm totally fine, just wanted to have the discussion to think it through. Thanks again for introducing the `Stream` based approach!
